server:
  port: 8888
spring:
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://13.125.176.46:3306/break_employment?serverTimezone=UTC&characterEncoding=UTF-8"
    username: jd
    password: jd1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true